HotelProject/HotelProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from superIndex import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^main/',include('superIndex.urls')),
    url(r'^standard_room/',include('superIndex.urls')),
    url(r'^login/',include('superIndex.urls')),
    url(r'^registration/',include('superIndex.urls')),
    url(r'^luxury_room/',include('superIndex.urls')),
    url(r'^logout/$',views.user_logout,name= 'logout')
]

HotelProject/superIndex/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from superIndex import views
from django.contrib.auth import views as auth_views

app_name = 'superIndex'
urlpatterns = [
    url(r'^standard_room/$',views.standard_room,name='standard_room'),
    url(r'^registration/$',views.registration,name='registration'),
    url(r'^luxury_room/$',views.luxury_room,name='luxury_room'),
    url(r'^login/$',views.user_login,name='login'),
]

HotelProject/superIndex/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User


# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete='models.CASCADE')
    cust_id = models.AutoField(primary_key=True)
    cust_name = models.CharField(max_length=264)
    address = models.CharField(max_length=264)
    SEX_CHOICES = (
        ('F', 'Female',),
        ('M', 'Male',),
        ('U', 'Unsure',),
    )
    gender = models.CharField(max_length = 9,choices=SEX_CHOICES)
    govt_proof = models.CharField(max_length = 264)
    contact_num = models.BigIntegerField()


    def __str__(self):
        return str(self.cust_name)

class Room(models.Model):
    room_id = models.AutoField(primary_key=True)
    room_type = models.CharField(max_length = 264)
    room_num = models.CharField(max_length = 264)
    floor = models.CharField(max_length = 264)
    avail = models.CharField(max_length = 264)
    price = models.CharField(max_length = 264)

    def __str__(self):
        return str(self.room_num)


class Booking(models.Model):
    booking_id = models.AutoField(primary_key=True)
    room_id = models.ForeignKey(Room,on_delete=models.CASCADE)
    cust_id = models.ForeignKey(Customer,on_delete=models.CASCADE)
    amount = models.CharField(max_length = 264)


    def __str__(self):
        return str(self.room_id)

HotelProject/superIndex/forms.py
from django import forms
from superIndex.models import Customer
from django.contrib.auth.models import User

class User_Form(forms.ModelForm):
    password =  forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ("username","email","password")

class Customer_Form(forms.ModelForm):
    sex = (('M','Male'),
            ('F','Female')
    )
    gender = forms.ChoiceField(choices=sex)
    class Meta():
        model = Customer
        fields = ("cust_id","cust_name",'address','gender','govt_proof','contact_num')

HotelProject/superIndex/views.py
from django.shortcuts import render
from django.conf.urls import url
from superIndex.forms import Customer_Form,User_Form
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required




# Create your views here.
def index(request):
    return render(request,'superIndex/homepage.html')

def standard_room(request):
    return render(request,'superIndex/standard_room.html')

def luxury_room(request):
    return render(request,'superIndex/luxury_room.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def registration(request):
    register = False

    if request.method == "POST":
        userform = User_Form(data=request.POST)
        customerform = Customer_Form(data=request.POST)

        if userform.is_valid() and customerform.is_valid():
            user = userform.save()
            user.set_password(user.password)
            user.save()

            customer = customerform.save(commit=False)
            customer.user = user
            customer.save()

            register = True
            return index(request)
        else:
            print(User_Form.errors,Customer_Form.errors)


    else:
        userform = User_Form()
        customerform = Customer_Form()
        return render(request,'superIndex/registration.html',
                                {'userform':userform,
                                 'customerform':customerform,
                                 'register':register
                                })

def user_login(request):

    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account Not Active!")
        else:
            print("Someone Tried to login but failed")
            print("Username: {} and Password : {}.format(username,password)")
            return HttpResponse('Invalid login details provided')
    else:
        return render(request,'superIndex/login.html',{})

HotelProject/templates/superIndex/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<title>CozyNest</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'carausel/carausel.css' %}">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
 <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="{% static 'carausel/carausel.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


<body>

<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-wide w3-padding w3-card">
    <a href="{% url 'index'%}" class="w3-bar-item w3-button"><b>HotelGrandPalace</b></a>
    <a href="{% url 'admin:index'%}" class="w3-bar-item w3-button">Admin</a>
    <!-- Float links to the right. Hide them on small screens -->
    <div class="w3-right w3-hide-small">
      <a href="#projects" class="w3-bar-item w3-button">Rooms</a>
      {% if user.is_authenticated %}

        <a href="{% url 'logout' %}" class="w3-bar-item w3-button">Logout</a>

      {% else %}

        <a href="{% url 'superIndex:login' %}" class="w3-bar-item w3-button">Login</a>

      {% endif %}

      <a href="{% url 'superIndex:registration' %}" class="w3-bar-item w3-button">Sign Up</a>
    </div>
  </div>
  </div>

<div class="container">
  <br>
  {% block body_block %}
  <!-- Anything you extend on this will be inherited in the templates -->
  {% endblock %}
<br>

HotelProject/templates/superIndex/homepage.html
<!DOCTYPE html>

{% extends 'superIndex/base.html' %}
{% block body_block %}
{% load staticfiles %}
<!-- Header -->
<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
  <img class="w3-image" src="{% static "images/homepage/webpageimage.jpg" %}" alt="Architecture" width=auto height="800">
  <div class="w3-display-middle w3-margin-top w3-center">
    <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>Hotel</b></span> <span class="w3-padding-small w3-text-orange">Grand Palace</span></h1>
  </div>
</header>

<!-- Page content -->
<div class="w3-content w3-padding" style="max-width:1564px">

  <!-- Project Section -->
  <div class="w3-container w3-padding-32" id="projects">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Room Types</h3>
  </div>

  <div class="w3-row-padding">
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-black w3-padding">Standard</div>
        <!--Creating the link to other pages-->
        <a href="{% url 'superIndex:standard_room' %}">
          <img src="{% static "images/homepage/sd-double_bed.jpg" %}" alt="House" style="width:100%">
        </a>
      </div>
    </div>
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-black w3-padding">Delux</div>
        <!--Creating the link to other pages-->
        <a href="{% url 'superIndex:luxury_room' %}">
        <img src="{% static "images/homepage/luxuryhome.jpg" %}" alt="House" style="width:100%">
      </a>
      </div>
    </div>
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-black w3-padding">Honeymoon Suites</div>
        <img src="{% static "images/homepage/honeymoonsuiteshome.jpg" %}" alt="House" style="width:100%">
      </div>
    </div>
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-black w3-padding">Dormetories</div>
        <img src="{% static "images/homepage/dormetorieshome.jpg" %}" alt="House" style="width:100%">
      </div>
    </div>
  </div>


  <!-- Facilities Section -->
  <br>
  <div class="w3-container w3-padding-32" id="facilities">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Facilities</h3>
    <div class="row">
      <div class="w3-col 3 m6 w3-margin-bottom">
        <div class="w3-display-container">

          <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
              <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <img  src="{% static "images/homepage/gardenspace.jpg" %}" alt="standard" style="width:100%; height:80%;"/>
                    </div>

              <div class="item">
                <img src="{% static "images/homepage/carparking.jpg" %}" alt="luxury" style="width:100%; height:80%;">
              </div>

              <div class="item">
              <img src="{% static "images/homepage/swimmingpool.jpg" %}" alt="Chicago" style="width:100%; height:80%;"/>
              </div>

              <div class="item">
              <img src="{% static "images/homepage/restaurant.jpg" %}" alt="Chicago" style="width:100%; height:80%;"/>
              </div>

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
      </div>
      <div class="w3-col 3 m6 w3-margin-bottom">
        <div class="w3-display-container" style="margin-left:10%">
          <h4><strong>Our Complementaries</strong></h4>
          <ul>
            <li>Bed Tea</li>
            <li>Breakfast</li>
            <li>Lunch</li>
            <li>Dinner</li>
          </ul>
          <h4><strong>Our Amenities</strong></h4>
          <ul>
            <li>Swimming Pool</li>
            <li>Cafeteria</li>
            <li>Bar & Restaurant</li>
            <li>Lift Facility</li>
            <li>Car Parking</li>
            <li>24/7 Electricity,Water & Security</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="w3-row-padding w3-grayscale">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Improvements & Bookings</h3>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="{% static "images/homepage/maintenance.jpg" %}" alt="John" style="width:100%">
      <h3>Maintanace</h3>
      <p class="w3-opacity">Place your Valuable comments</p>
      <p>Please click on the Contact button to help us to improve our services.</p>
      <p><button class="btn btn-primary w3-block">Contact</button></p>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="{% static "images/homepage/lost&found.png" %}" alt="Jane" style="width:100%">
      <h4>Lost & Found</h4>
      <p class="w3-opacity">Inform about your loss</p>
      <p>If you forget something click here to inform.</p>
      <p><button class="w3-button btn btn-success w3-block">I Lost</button></p>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="{% static "images/homepage/customerparking.jpg" %}" alt="Mike" style="width:100%">
      <h3>Parking</h3>
      <p class="w3-opacity">Book a space</p>
      <p>Get a space for your vehicle by clicking the GET PARKED button.</p>
      <p><button class="w3-button btn btn-warning w3-block">Get Parked</button></p>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="{% static "images/homepage/corporate.jpg" %}" alt="Dan" style="width:100%">
      <h4>Coorporate Bookings</h4>
      <p class="w3-opacity">For office party and conference</p>
      <p> For Corporate meetings and party's, we share our facilities.</p>
      <p><button class="w3-button btn btn-danger w3-block">We'r Corporates</button></p>
    </div>
  </div>

  <!-- Contact Section -->
  <br>
  <div class="w3-container w3-padding-32" id="contact">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Contact</h3>
    <p>Fill up the fom we will get in touch with you.</p>
    <form action="/action_page.php" target="_blank">
      <input class="w3-input w3-border" type="text" placeholder="Name" required name="Name">
      <input class="w3-input w3-section w3-border" type="text" placeholder="Email" required name="Email">
      <input class="w3-input w3-section w3-border" type="text" placeholder="Subject" required name="Subject">
      <input class="w3-input w3-section w3-border" type="text" placeholder="Comment" required name="Comment">
      <button class="w3-button w3-black w3-section" type="submit">
        <i class="fa fa-paper-plane"></i> SEND MESSAGE
      </button>
    </form>
  </div>

<!-- Image of location/map -->
<div class="w3-container">
<img src="{% static "images/homepage/.jpg" %}" alt="Jane" class="w3-image" style="width:100%">
</div>
<!-- End page content -->
</div>
{% endblock %}

<!-- Footer -->
<footer class="w3-center w3-black w3-padding-16">
  <p>Project by <strong>Debayan Paul</strong></p>
</footer>

</body>
</html>

HotelProject/templates/superIndex/login.html
<!DOCTYPE html>

{% extends 'superIndex/base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block body_block %}
<br><br>
<div class="row">
  <div class="col-md-2">

  </div>
  <div class="col-md-8">
    <div class='jumbotron'>
      <h1>Please Login</h1><br>
      <form action="{% url 'superIndex:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username : </label>
          <input class="form-control" type="text" name='username' placeholder="Enter Username">
          <label for="password">Password :</label>
          <input class="form-control" type="text" name="password"><BR><br>
          <input type="submit" value="Login" class="btn btn-success">
        </div>

      </form>
    </div>

  </div>
  <div class="col-md-2">

  </div>
</div>
    </form>
  </div>

{% endblock %}

HotelProject/templates/superIndex/luxury_room.html
<!DOCTYPE html>

{% extends 'superIndex/base.html' %}
{% block body_block %}
{% load staticfiles %}
<!--<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
  <img class="w3-image" src="{% static "images/homepage/topimage.jpg" %}" alt="Architecture" width=auto height="800">
  <div class="w3-display-middle w3-margin-top w3-center">
    <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>Hotel</b></span> <span class="w3-padding-small w3-text-orange">CozyNest</span></h1>
  </div>
</header>-->
<br>
<div class="w3-container w3-padding-32" id="about">
  <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Luxury Double Bed</h3>
  <div class="row">
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container">

      <!--  <img src="{% static "images/homepage/topimage.jpg" %}" alt="House" style="width:100%">-->
      <!--Startof carausel-->

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
          <img  src="{% static "images/homepage/gardenspace.jpg" %}" alt="luxury" style="width:100%; height:80%;"/>
      </div>

      <div class="item">
        <img  src="{% static "images/homepage/gardenspace.jpg" %}" alt="standard" style="width:100%; height:80%;"/>
      </div>

      <div class="item">
        <img  src="{% static "images/homepage/gardenspace.jpg" %}" alt="standard" style="width:100%; height:80%;"/>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


      <!--Startof carausel-->
      </div>
    </div>
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container" style="margin-left:10%">
        <h4><strong>Our Complementaries</strong></h4>
        <ul>
          <li>Bed Tea</li>
          <li>Breakfast</li>
          <li>Lunch</li>
          <li>Dinner</li>
        </ul>
        <h4><strong>Our Amenities</strong></h4>
        <ul>
          <li>Swimming Pool</li>
          <li>Cafeteria</li>
          <li>Bar & Restaurant</li>
          <li>Lift Facility</li>
          <li>Car Parking</li>
          <li>24/7 Electricity,Water & Security</li>
        </ul>
        <br>
        <a href="{% url 'superIndex:registration' %}">
          <button class="btn btn-success" type="button" name="button">Book Now!!</button>
        </a>
      </div>
    </div>

<div class="w3-container w3-padding-32" id="about">
  <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Luxury Triple Bedrooms</h3>
  <div class="row">
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <h4><strong>Our Complementaries</strong></h4>
        <ul>
          <li>Bed Tea</li>
          <li>Breakfast</li>
          <li>Lunch</li>
          <li>Dinner</li>
        </ul>
        <h4><strong>Our Amenities</strong></h4>
        <ul>
          <li>Swimming Pool</li>
          <li>Cafeteria</li>
          <li>Bar & Restaurant</li>
          <li>Lift Facility</li>
          <li>Car Parking</li>
          <li>24/7 Electricity,Water & Security</li>
        </ul>
        <input type="submit" class="btn btn-success" value="Book Now!">
      </div>
    </div>
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container" style="margin-left:10%">
        <img src="{% static "images/homepage/topimage.jpg" %}" alt="House" style="width:100%">

      </div>
    </div>
{% endblock %}


</html>

HotelProject/templates/superIndex/registration.html
<!DOCTYPE html>

{% extends 'superIndex/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
{% load staticfiles %}
<br><br><br>

<div class="container-fluid">

  <div class="row">
    <div class="col-md-3">

      <!--




     -->

    </div>
    <div class="col-md-6">
      {% if register %}
        <h1>Thank you for registering</h1>
      {% else %}
      <form method="POST" class="form-group">
        <h1>Please register here</h1>
          <div class="form-group">

            {{ userform|crispy }}

          </div>
          <div class="form-group">

            {{ customerform|crispy }}

          </div>

            {% csrf_token %}

      <input class="btn btn-success" type="submit" value="Register">

      </form>

      {% endif %}

    </div>

    <div class="col-md-3">

    </div>
  </div>


</div>


{% endblock %}

HotelProject/templates/superIndex/standard_room.html
<!DOCTYPE html>

{% extends 'superIndex/base.html' %}
{% block body_block %}
{% load staticfiles %}
<!--<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
  <img class="w3-image" src="{% static "images/homepage/topimage.jpg" %}" alt="Architecture" width=auto height="800">
  <div class="w3-display-middle w3-margin-top w3-center">
    <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>Hotel</b></span> <span class="w3-padding-small w3-text-orange">CozyNest</span></h1>
  </div>
</header>-->
<br>
<div class="w3-container w3-padding-32" id="about">
  <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Standard Double Bed</h3>
  <div class="row">
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container">

      <!--  <img src="{% static "images/homepage/topimage.jpg" %}" alt="House" style="width:100%">-->
      <!--Startof carausel-->

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <a href="https://www.tripadvisor.in/LocationPhotoDirectLink-g317096-d10100907-i259423666-Hotel_Madni_Royale-Ajmer_Ajmer_District_Rajasthan.html#259423666"><img alt="" src="https://media-cdn.tripadvisor.com/media/photo-s/0f/76/7d/aa/standard-room-indian.jpg"/></a><br/>
            </div>

      <div class="item">
        <img src="{% static "images/homepage/sd-double_bed.jpg" %}" alt="Chicago" style="width:100%; height:80%;">
      </div>

      <div class="item">
        <img src=<a href="https://www.tripadvisor.in/LocationPhotoDirectLink-g317096-d10100907-i259423666-Hotel_Madni_Royale-Ajmer_Ajmer_District_Rajasthan.html#259423666"><img alt="" src="https://media-cdn.tripadvisor.com/media/photo-s/0f/76/7d/aa/standard-room-indian.jpg"/></a><br/>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


      <!--Startof carausel-->
      </div>
    </div>
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container" style="margin-left:10%">
        <h4><strong>Our Complementaries</strong></h4>
        <ul>
          <li>Bed Tea</li>
          <li>Breakfast</li>
        </ul>
        <h4><strong>Our Amenities</strong></h4>
        <ul>
          <li>Swimming Pool</li>
          <li>Cafeteria</li>
          <li>Bar & Restaurant</li>
          <li>Lift Facility</li>
          <li>Car Parking</li>
          <li>24/7 Electricity,Water & Security</li>
        </ul>
        <a href="{% url 'superIndex:registration' %}">
          <button class="btn btn-success "type="button" name="button">Book Now!!</button>
        </a>
      </div>
    </div>
  </div>
</div>
<div class="w3-container w3-padding-32" id="about">
  <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Standard Triple Bedrooms</h3>
  <div class="row">
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <h4><strong>Our Complementaries</strong></h4>
        <ul>
          <li>Bed Tea</li>
          <li>Breakfast</li>
        </ul>
        <h4><strong>Our Amenities</strong></h4>
        <ul>
          <li>Swimming Pool</li>
          <li>Cafeteria</li>
          <li>Bar & Restaurant</li>
          <li>Lift Facility</li>
          <li>Car Parking</li>
          <li>24/7 Electricity,Water & Security</li>
        </ul>
        <input type="submit" class="btn btn-success" value="Book Now!">
      </div>
    </div>
    <div class="w3-col 3 m6 w3-margin-bottom">
      <div class="w3-display-container" style="margin-left:10%">
        <img src="{% static "images/homepage/topimage.jpg" %}" alt="House" style="width:100%">

      </div>
    </div>
{% endblock %}


</html>